# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colab.
**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import RDF, Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
DATA = Namespace("http://data.org#")

for person in g1.subjects(RDF.type, DATA.Person):
    if (person, None, None) in g2:
        for prop in [VCARD.Given, VCARD.Family, VCARD.EMAIL]:
            if not (person, prop, None) in g1:
                value = g2.value(person, prop)
                if value:
                    g1.add((person, prop, value))

for s, p, o in g1:
    print(s, p, o)