# -*- coding: utf-8 -*-
"""Task09.ipynb
Automatically generated by Colab.
**Task 09: Data linking**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials/"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g3 = Graph()
g1.parse(github_storage+"rdf/data03.rdf", format="xml")
g2.parse(github_storage+"rdf/data04.rdf", format="xml")

"""Busca individuos en los dos grafos y enlázalos mediante la propiedad OWL:sameAs, inserta estas coincidencias en g3. Consideramos dos individuos iguales si tienen el mismo apodo y nombre de familia. Ten en cuenta que las URI no tienen por qué ser iguales para un mismo individuo en los dos grafos."""

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
OWL = Namespace("http://www.w3.org/2002/07/owl#")

query = """
PREFIX vcard: <http://www.w3.org/2001/vcard-rdf/3.0#>
SELECT ?person ?fn ?family
WHERE {
  ?person vcard:FN ?fn ;
          vcard:Family ?family .
}
"""

people_g1 = [(row.person, row.fn, row.family) for row in g1.query(query)]
people_g2 = [(row.person, row.fn, row.family) for row in g2.query(query)]

for uri1, fn1, fam1 in people_g1:
    for uri2, fn2, fam2 in people_g2:
        if fn1 == fn2 and fam1 == fam2:
            g3.add((URIRef(uri1), OWL.sameAs, URIRef(uri2)))

for s, p, o in g3:
    print(s, p, o)