# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/AlexFerroni02/Curso2025-2026-ODKG/blob/assignment-4/Assignment4/course_materials/notebooks/Task06.ipynb

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# this task is validated in the next step

ontology = Namespace("http://www.oeg-upm.net/Ontology#")
person = Namespace("http://oeg.fi.upm.es/def/people#")

# Bind the namespaces to the graph
g.bind("ontology", ontology)
g.bind("person", person)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

# TO DO
g.namespace_manager.bind('rdfs', RDFS)
g.namespace_manager.bind('rdf', RDF)
g.namespace_manager.bind('xsd', XSD)

taxonomy = {
    'Person': None,
    'Professor': 'Person',
    'FullProfessor': 'Professor',
    'AssociateProfessor': 'Professor',
    'InterimAssociateProfessor': 'AssociateProfessor'
}

# Aggiungo le classi al grafo
for cls, parent in taxonomy.items():
    cls_uri = person[cls]
    g.add((cls_uri, RDF.type, RDFS.Class))
    g.add((cls_uri, RDFS.label, Literal(cls, datatype=XSD.string)))
    if parent:
        g.add((cls_uri, RDFS.subClassOf, person[parent]))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

# TO DO
properties = {
    'hasColleague': {
        'domain': person.Person,
        'range': person.Person
    },
    'hasHomePage': {
        'domain': person.FullProfessor,
        'range': RDFS.Literal
    },
    'hasName': {
        'domain': person.Person,
        'range': RDFS.Literal
    }
}

for prop, info in properties.items():
    prop_uri = person[prop]
    g.add((prop_uri, RDF.type, RDF.Property))
    g.add((prop_uri, RDFS.label, Literal(prop, datatype=XSD.string)))
    g.add((prop_uri, RDFS.domain, info['domain']))
    g.add((prop_uri, RDFS.range, info['range']))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

# TO DO
data = Namespace("http://oeg.fi.upm.es/resource/person/")
g.namespace_manager.bind('data', data)


individuals = {
    'Raul': person.InterimAssociateProfessor,
    'Asun': person.FullProfessor,
    'Oscar': person.AssociateProfessor
}

for ind, cls in individuals.items():
    ind_uri = data[ind]
    g.add((ind_uri, RDF.type, cls))
    g.add((ind_uri, RDFS.label, Literal(ind, datatype=XSD.string)))


g.add((data.Raul, person.hasColleague, data.Asun))
g.add((data.Asun, person.hasColleague, data.Raul))
g.add((data.Asun, person.hasHomePage, Literal("http://www.oeg-upm.net/", datatype=XSD.string)))
g.add((data.Oscar, person.hasColleague, data.Asun))
g.add((data.Oscar, person.hasName, Literal("Oscar", datatype=XSD.string)))


for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

# TO DO
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
foaf = Namespace("http://xmlns.com/foaf/0.1/")

# Aggiungo i namespace al grafo
g.namespace_manager.bind('vcard', vcard)
g.namespace_manager.bind('foaf', foaf)

# Aggiungo le proprietà per Oscar usando le proprietà target
# Email usando FOAF.email
g.add((data.Oscar, foaf.email, Literal("oscar@example.com", datatype=XSD.string)))

# Given name usando VCARD.Given
g.add((data.Oscar, vcard.Given, Literal("Oscar", datatype=XSD.string)))

# Family name usando VCARD.Family
g.add((data.Oscar, vcard.Family, Literal("Garcia", datatype=XSD.string)))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")