# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iAyX2S2WqMHUZJcaErfBj16O1KuJ89ws

**Task 06: Modifying RDF(s)**
"""

##!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# this task is validated in the next step
people_prefix = Namespace("http://oeg.fi.upm.es/def/people#")
ontology_prefix = Namespace("http://www.oeg-upm.net/ontologies/ontology#")

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

# TO DO

uri_person = people_prefix.Person
uri_professor = people_prefix.Professor
uri_associate_professor = people_prefix.AssociateProfessor
uri_interim_associate_professor = people_prefix.InterimAssociateProfessor
uri_full_professor = people_prefix.FullProfessor

g.add((uri_person, RDF.type, RDFS.Class))
g.add((uri_person, RDFS.label, Literal("Person", datatype=XSD.string)))
g.add((uri_professor, RDF.type, RDFS.Class))
g.add((uri_professor, RDFS.label, Literal("Professor", datatype=XSD.string)))
g.add((uri_associate_professor, RDF.type, RDFS.Class))
g.add((uri_associate_professor, RDFS.label, Literal("AssociateProfessor", datatype=XSD.string)))
g.add((uri_interim_associate_professor, RDF.type, RDFS.Class))
g.add((uri_interim_associate_professor, RDFS.label, Literal("InterimAssociateProfessor", datatype=XSD.string)))
g.add((uri_full_professor, RDF.type, RDFS.Class))
g.add((uri_full_professor, RDFS.label, Literal("FullProfessor", datatype=XSD.string)))

g.add((uri_professor, RDFS.subClassOf, uri_person))
g.add((uri_associate_professor, RDFS.subClassOf, uri_professor))
g.add((uri_interim_associate_professor, RDFS.subClassOf, uri_associate_professor))
g.add((uri_full_professor, RDFS.subClassOf, uri_professor))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

# TO DO

property_hasName = people_prefix.hasName
property_hasHomePage = people_prefix.hasHomePage
property_hasColleague = people_prefix.hasColleague

g.add((property_hasName, RDF.type, RDF.Property))
g.add((property_hasName, RDFS.label, Literal("hasName", datatype=XSD.string)))
g.add((property_hasName, RDFS.domain, uri_person))
g.add((property_hasName, RDFS.range, RDFS.Literal))

g.add((property_hasColleague, RDF.type, RDF.Property))
g.add((property_hasColleague, RDFS.label, Literal("hasColleague", datatype=XSD.string)))
g.add((property_hasColleague, RDFS.domain, uri_person))
g.add((property_hasColleague, RDFS.range, uri_person))

g.add((property_hasHomePage, RDF.type, RDF.Property))
g.add((property_hasHomePage, RDFS.label, Literal("hasHomePage", datatype=XSD.string)))
g.add((property_hasHomePage, RDFS.domain, uri_full_professor))
g.add((property_hasHomePage, RDFS.range, RDFS.Literal))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

# TO DO
# Visualize the results

person_prefix = Namespace("http://oeg.fi.upm.es/resource/person/")

oscar = person_prefix.Oscar
asun = person_prefix.Asun
raul = person_prefix.raul

g.add((oscar, RDF.type, uri_associate_professor))
g.add((oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))

g.add((asun, RDF.type, uri_full_professor))
g.add((asun, RDFS.label, Literal("Asun", datatype=XSD.string)))

g.add((raul, RDF.type, uri_interim_associate_professor))
g.add((raul, RDFS.label, Literal("Raul", datatype=XSD.string)))

g.add((oscar, property_hasColleague, asun))
g.add((asun, property_hasColleague, raul))


# 2B. Añadir las Propiedades de Dato (Enlaces a Literales)
g.add((oscar, property_hasName, Literal("Óscar Corcho García")))
g.add((asun, property_hasHomePage, Literal("http://www.oeg-upm.net/")))


for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

# TO DO

vcard_prefix = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
foaf_prefix = Namespace("http://xmlns.com/foaf/0.1/")

g.add((oscar, vcard_prefix.Given, Literal("Óscar", datatype=XSD.string)))
g.add((oscar, vcard_prefix.Family, Literal("Corcho García", datatype=XSD.string)))
g.add((oscar, foaf_prefix.email, Literal("gmaildeoscar@gmaildeprueba.es")))


# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")