# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJ7jDL-Wj_WrjZp3113QsBS7H-5qayzX

**Task 06: Modifying RDF(s)**
"""

# !pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

ont = Namespace("http://oeg.fi.upm.es/def/people#")
per = Namespace("http://oeg.fi.upm.es/resource/person/")
g.bind("ont", ont)
g.bind("per", per)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

# TO DO
# Clase= var
Person = ont.Person
Professor = ont.Professor
FullProfessor = ont.FullProfessor
AssociateProfessor = ont.AssociateProfessor
InterimAssociateProfessor = ont.InterimAssociateProfessor

# declarar cada uris como clase de rdfs
g.add((Person, RDF.type, RDFS.Class))
g.add((Professor,RDF.type,RDFS.Class))
g.add((FullProfessor, RDF.type, RDFS.Class))
g.add((AssociateProfessor, RDF.type, RDFS.Class))
g.add((InterimAssociateProfessor, RDF.type, RDFS.Class))

# declarando las jerarquias
g.add((Professor, RDFS.subClassOf, Person))
g.add((FullProfessor,RDFS.subClassOf,Professor))
g.add((AssociateProfessor,RDFS.subClassOf, Professor))
g.add((InterimAssociateProfessor,RDFS.subClassOf, AssociateProfessor))

# etiquetas
g.add((Person, RDFS.label, Literal("Person",datatype=XSD.string)))
g.add((Professor, RDFS.label, Literal("Professor",datatype=XSD.string)))
g.add((FullProfessor, RDFS.label, Literal("FullProfessor",datatype=XSD.string)))
g.add((AssociateProfessor, RDFS.label, Literal("AssociateProfessor",datatype=XSD.string)))
g.add((InterimAssociateProfessor, RDFS.label, Literal("InterimAssociateProfessor",datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

# TO DO
#crear variables para hasName, Has Colleague, hasHomePage
HasName = per.hasName
HasColleague = per.hasColleague
HasHomePage = per.hasHomePage

# declarar cada uris como propiedad de rdfs
g.add((HasName, RDF.type, RDF.Property))
g.add((HasColleague, RDF.type, RDF.Property))
g.add((HasHomePage, RDF.type, RDF.Property))

# dominio y rango
g.add((HasName,RDFS.domain,Person))
g.add((HasName,RDFS.range,RDFS.Literal))
g.add((HasColleague,RDFS.domain,Person))
g.add((HasColleague,RDFS.range,Person))
g.add((HasHomePage,RDFS.domain,FullProfessor))
g.add((HasHomePage,RDFS.range,RDFS.Literal))

# etiquetas
g.add((HasName, RDFS.label, Literal("hasName",datatype=XSD.string)))
g.add((HasColleague, RDFS.label, Literal("hasColleague",datatype=XSD.string)))
g.add((HasHomePage, RDFS.label, Literal("hasHomePage",datatype=XSD.string)))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

# TO DO
# Definir un nuevo prefijo para los datos
data = Namespace("http://oeg.fi.upm.es/resource/person/")
g.bind('data', data)

Oscar = data.Oscar
Asun = data.Asun
Raul = data.Raul

g.add((Oscar,RDF.type,AssociateProfessor))
g.add((Asun,RDF.type,FullProfessor))
g.add((Raul,RDF.type,InterimAssociateProfessor))

g.add((Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((Asun, RDFS.label, Literal("Asun", datatype=XSD.string)))
g.add((Raul, RDFS.label, Literal("Raul", datatype=XSD.string)))

g.add((Oscar,per.hasName, Literal ("Oscar Corcho García",datatype=XSD.string)))
g.add((Oscar,per.hasColleague, Asun))
g.add((Asun,per.hasColleague,Raul))
g.add((Asun,per.hasHomePage, Literal("http://www.oeg-upm.net/")))

# Visualize the results
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

# TO DO
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
FOAF = Namespace("http://xmlns.com/foaf/0.1/")

g.add((per.Oscar, VCARD.Family, Literal("Óscar", datatype=XSD.string)))
g.add((per.Oscar, VCARD.Given, Literal("Corcho García", datatype=XSD.string)))
g.add((per.Oscar, FOAF.email, Literal("gmaildeoscar@gmaildeprueba.es", datatype=XSD.string)))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")